<?php

########################################################################
# Extension Manager/Repository config file for ext: "dl_dropboxsync"
#
# Auto generated by Extension Builder 2012-02-28
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Dropbox Sync',
	'description' => 'Syncs data from a dropbox folder to a fileadmin folder.',
	'category' => 'misc',
	'author' => 'Daniel Lienert',
	'author_email' => 'daniel@lienert.cc',
	'author_company' => 'Daniel Lienert',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3.0',
			'fluid' => '1.3.0',
			'pt_extbase' => '0.1.4',
			'pt_extlist' => '0.5.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>